# Generated by Django 3.0.3 on 2020-05-23 08:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reddit_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='created_post_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
